dist: xenial
language: cpp
compiler: gcc
python:
  - 3.6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
before_install:
- sudo apt-get update
- sudo apt-get install python3
- pip install --upgrade pip
install:
- pip3 install conan
- conan user
script:
- cmake --version
- export CC=gcc-7
- export CXX=g++-7
- conan install .
- cmake .
- make
