dist: xenial
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
install:
- sudo snap install cmake --beta --classic
- pip install conan
- conan user
script:
- cmake --version
- export CC=gcc-7
- export CXX=g++-7
- conan install .
- cmake .
- make
