dist: xenial
language: cpp
compiler: 
- gcc
install:
- pip install conan
- conan user
script:
- mkdir build
- cd build
- ls /home/travis/build/winmord/travis_test/src/travis_test/include/travis_test
- conan install ..
- cmake ..
- make
