dist: xenial
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3
      - python3-pip
      - gcc-7
      - g++-7
install:
- pip install conan --upgrade
- pip install conan_package_tools
- alias python=python3
- conan user
script:
- export CC=gcc-7
- export CXX=g++-7
- conan install .
- cmake .
- make
