dist: xenial
language: cpp
compiler: gcc
addons:
  apt:
    packages:
      - gcc-7
      - g++-7
install:
- pip3 install --upgrade pip setuptools
- pip3 install conan cmake
- conan user
script:
- export CC=gcc-7
- export CXX=g++-7
- conan install .
- cmake .
- make
