dist: xenial
language: python
python:
  - "3.7"
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
install:
- sudo pip install conan --upgrade
- sudo pip install conan_package_tools
- conan user usr
script:
- export CC=gcc-9
- export CXX=g++-9
- conan profile new default --detect
- conan profile update settings.compiler.libcxx=libstdc++11 default
- conan remote clean
- conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
- conan install .
- cmake .
- make
