dist: xenial
language: cpp
compiler: gcc
addons:
  snaps:
    - name: cmake
    confinement: classic
    channel: 3.19/candidate
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
install:
- pip install conan
- conan user
script:
- export CC=gcc-7
- export CXX=g++-7
- cmake --version
- conan install .
- cmake .
- make
