dist: xenial
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-
install:
- pip install conan
- conan user
script:
- export CC=gcc-7
- export CXX=g++-7
- conan profile new default --detect
- conan profile update settings.compiler.libcxx=libstdc++17 default
- conan install .
- cmake .
- make
