dist: xenial
language: python
python:
  - "3.7"
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
install:
- sudo pip install conan --upgrade
- sudo pip install conan_package_tools
- conan user
script:
- export CC=gcc-7
- export CXX=g++-7
- conan install .
- cmake .
- make
