dist: xenial
language: cpp
compiler: 
- gcc
install:
- pip install conan
- conan user
script:
- echo ${CONAN_DEFAULT_PROFILE_PATH}
- conan profile update settings.compiler.libcxx=libstdc++17 default
- conan install .
- cmake .
- make
