dist: xenial
language: cpp
compiler: gcc
python:
  - 3.5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
install:
- pip install conan
- conan user
script:
- python3 --version
- cmake --version
- export CC=gcc-7
- export CXX=g++-7
- conan install .
- cmake .
- make
