dist: xenial
language: python
python:
  - "3.7"
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
install:
- sudo pip install conan --upgrade
- sudo pip install conan_package_tools
- conan user
script:
- export CC=gcc-9
- export CXX=g++-9
- conan install .
- cmake .
- make
