dist: xenial
language: cpp
compiler: 
- gcc
install:
- pip install conan
- conan user
script:
- ls /home/travis/.conan/profiles
- conan profile update settings.compiler.libcxx=libstdc++17 default
- conan install .
- cmake .
- make
